version: '3.8'

networks:
  smf-network:
    driver: bridge

services:
  pdu-session:
    build:
      context: .
      dockerfile: pdu-session/Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=8081
      - LOGLEVEL=DEBUG
      - INSTANCE_ID=pdu-session-node
      - GW_PORT=8080
    networks:
      - smf-network

  # pdu-session-2:
  #   build:
  #     context: .
  #     dockerfile: pdu-session/Dockerfile
  #   hostname: pdu-session-2
  #   environment:
  #     - HOST=0.0.0.0
  #     - PORT=8081
  #     - LOGLEVEL=DEBUG
  #     - INSTANCE_ID=pdu-session-node
  #     - GW_PORT=8080
  #   networks:
  #   - smf-network

  # pdu-session-3:
  #   build:
  #     context: .
  #     dockerfile: pdu-session/Dockerfile
  #   hostname: pdu-session-3
  #   environment:
  #     - HOST=0.0.0.0
  #     - PORT=8081
  #     - LOGLEVEL=DEBUG
  #     - INSTANCE_ID=pdu-session-node
  #     - GW_PORT=8080
  #   networks:
  #   - smf-network

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - LOGLEVEL=DEBUG
      - PDU_SERVICE_NAME=pdu-session
      - PDU_PORT=8081
    depends_on:
      - pdu-session
    networks:
      - smf-network